version: '3'
services:
  auth_db:
    container_name: auth_db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: accounts
      POSTGRES_PASSWORD: root
